name: lingap
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  persistent_bottom_nav_bar: ^6.2.1
  curved_navigation_bar: ^1.0.6
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.1
  supabase_auth_ui: ^0.5.1
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  videosdk: ^1.2.2
  http: ^1.2.2
  flutter_blue_plus: ^1.34.5
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  record: ^5.2.0
  health: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  assets:
    - assets/logo.png
    - assets/test.jpg
    - assets/mood/cheerful.png
    - assets/mood/happy.png
    - assets/mood/neutral.png
    - assets/mood/sad.png
    - assets/mood/awful.png
    - assets/vitals/smartwatch.png
    - assets/vitals/heart.png
    - assets/vitals/blood.png
    - assets/vitals/sleep.png
    - assets/vitals/mood.png
