name: lingap
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  persistent_bottom_nav_bar: ^6.2.1
  curved_navigation_bar: ^1.0.6
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.1
  supabase_auth_ui: ^0.5.1
  google_sign_in: ^6.2.2
  cupertino_icons: ^1.0.8
  videosdk: ^1.2.2
  http: ^1.2.2
  flutter_blue_plus: ^1.34.5
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.2
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  record: ^5.2.0
  health: ^11.1.1
  workmanager: ^0.5.2
  shared_preferences: ^2.3.5
  audio_waveforms: ^1.2.0
  qr_code_dart_scan: ^0.9.4
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  dio: ^5.8.0+1
  geolocator: ^12.0.0
  lucide_icons: ^0.257.0
  speech_to_text: ^6.6.0
  flutter_tts: ^4.2.2
  web_socket_channel: ^3.0.2
  flutter_dotenv: ^5.2.1
  langchain: ^0.7.7+2
  langchain_pinecone: ^0.1.0+11
  langchain_openai: ^0.7.3
  dart_openai: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 700
  assets:
    - assets/logo.png
    - assets/test.jpg
    - assets/mood/cheerful.png
    - assets/mood/happy.png
    - assets/mood/neutral.png
    - assets/mood/sad.png
    - assets/mood/awful.png
    - assets/vitals/smartwatch.png
    - assets/vitals/heart.png
    - assets/vitals/blood.png
    - assets/vitals/sleep.png
    - assets/vitals/mood.png

    - assets/logo/google.png
    - assets/logo/facebook.png

    - assets/splashscreen/robot.png
    - assets/splashscreen/splash1.png
    - assets/splashscreen/splash2.png
    - assets/splashscreen/splash3.png
    - assets/splashscreen/splash4.png
    - assets/splashscreen/splash5.png
    - assets/splashscreen/splash6.png
    - assets/splashscreen/splash7.png
    - assets/splashscreen/data_privacy.png
    - assets/splashscreen/checked.png
    - assets/splashscreen/unchecked.png

    - assets/profile/profile1.png
    - assets/profile/profile2.png
    - assets/profile/profile3.png
    - assets/profile/profile4.png
    - assets/profile/profile5.png
    - assets/profile/profile6.png
    - assets/profile/profile7.png
    - assets/profile/profile8.png
    
    - assets/profileIcon/bg.png
    - assets/profileIcon/close.png
    - assets/profileIcon/dark.png
    - assets/profileIcon/emergency.png
    - assets/profileIcon/logout.png
    - assets/profileIcon/notification.png
    - assets/profileIcon/user.png

    - assets/journal/homebg.png
    - assets/journal/book.png
    - assets/journal/ekis.png
    - assets/journal/positive.png
    - assets/journal/negative.png
    - assets/journal/more.png
    - assets/journal/awful_frame.png
    - assets/journal/sad_frame.png
    - assets/journal/neutral_frame.png
    - assets/journal/happy_frame.png
    - assets/journal/cheerful_frame.png
    - assets/journal/time.png
    - assets/journal/mic.png
    - assets/journal/camera.png
    - assets/journal/record.png
    - assets/journal/stop.png
    - assets/journal/save.png
    - assets/journal/play.png
    - assets/journal/pause.png
    - assets/journal/created.png
    - assets/journal/cancel.png
    - assets/journal/trash.png
    - assets/journal/delete.png
    - assets/journal/edit.png
    - assets/journal/remove.png

    - assets/consultation/addiction.png
    - assets/consultation/anxiety.png
    - assets/consultation/children.png
    - assets/consultation/depression.png
    - assets/consultation/email.png
    - assets/consultation/food.png
    - assets/consultation/grief.png
    - assets/consultation/lgbtq.png
    - assets/consultation/no_appointment.png
    - assets/consultation/psychosis.png
    - assets/consultation/relationship.png
    - assets/consultation/schedule.png
    - assets/consultation/sleep.png
    - assets/consultation/telephone.png
    - assets/consultation/user.png
    - assets/consultation/professional-success.png
    - assets/consultation/finish.png
    - assets/consultation/camera.png
    - assets/consultation/bulb.png
    - assets/consultation/signal.png
    - assets/consultation/steth.png
    - assets/consultation/upcoming.png
    - assets/doctor.jpg

    - assets/peer/videocall.png
    - assets/peer/call.png
    - assets/peer/send.png
    - assets/peer/search.png

    - assets/chatbot/chatbot.png
    - assets/chatbot/limit.png
    - assets/chatbot/chat.png

    - assets/chatbot/icon/abstract.png
    - assets/chatbot/icon/arrowdown.png
    - assets/chatbot/icon/arrowup.png
    - assets/chatbot/icon/bandaid.png
    - assets/chatbot/icon/bell.png
    - assets/chatbot/icon/blood.png
    - assets/chatbot/icon/bulb.png
    - assets/chatbot/icon/calendar.png
    - assets/chatbot/icon/chart.png
    - assets/chatbot/icon/cloud.png
    - assets/chatbot/icon/control.png
    - assets/chatbot/icon/document.png
    - assets/chatbot/icon/drug.png
    - assets/chatbot/icon/ekg.png
    - assets/chatbot/icon/head.png
    - assets/chatbot/icon/healthplus.png
    - assets/chatbot/icon/heartbeat.png
    - assets/chatbot/icon/house.png
    - assets/chatbot/icon/leaf.png
    - assets/chatbot/icon/lock.png
    - assets/chatbot/icon/mask.png
    - assets/chatbot/icon/medal.png
    - assets/chatbot/icon/microscope.png
    - assets/chatbot/icon/performance.png
    - assets/chatbot/icon/phone.png
    - assets/chatbot/icon/piechart.png
    - assets/chatbot/icon/pill.png
    - assets/chatbot/icon/processor.png
    - assets/chatbot/icon/search.png
    - assets/chatbot/icon/shield_health.png
    - assets/chatbot/icon/stethoscope.png
    - assets/chatbot/icon/syringe.png
    - assets/chatbot/icon/time.png
    - assets/chatbot/icon/virus.png

    - assets/mindfulness/bg.png
    - assets/mindfulness/time.png

    - assets/tracker/darkYellow.png
    - assets/tracker/darkPurple.png
    - assets/tracker/darkBlue.png
    - assets/tracker/darkBrown.png
    - assets/tracker/darkGreen.png
    - assets/tracker/darkOrange.png
    - assets/tracker/moodYellow.png
    - assets/tracker/moodBlue.png
    - assets/tracker/moodBrown.png
    - assets/tracker/moodGreen.png
    - assets/tracker/moodOrange.png
    - assets/tracker/set_mood.png
    - assets/tracker/sleep_success.png


    - assets/lightMoods/lightCheerful.png
    - assets/lightMoods/lightHappy.png
    - assets/lightMoods/lightNeutral.png
    - assets/lightMoods/lightSad.png
    - assets/lightMoods/lightAwful.png

    - assets/whiteMoods/whiteGreen.png
    - assets/whiteMoods/whiteYellow.png
    - assets/whiteMoods/whiteBrown.png
    - assets/whiteMoods/whiteOrange.png
    - assets/whiteMoods/whiteBlue.png

    - assets/notification/data.png
    - assets/notification/exercise.png
    - assets/notification/journal.png
    - assets/notification/peer.png
    - assets/notification/session.png
    - assets/notification/appoint.png


