name: lingap
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  persistent_bottom_nav_bar: ^6.2.1
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.1
  supabase_auth_ui: ^0.5.1
  google_sign_in: ^6.2.2
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  videosdk: ^1.2.2
  http: ^1.2.2
  flutter_blue_plus: ^1.34.5
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/test.jpg